{% set name = "blitzgsea" %}
{% set version = "1.3.47" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/blitzgsea-{{ version }}.tar.gz
  sha256: 952fe66777b270e244d91ae6596fbdfba7ea12abd8376c56467a6beae2124a98

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pandas >=1.1.5
    - numpy
    - scikit-learn
    - tqdm
    - statsmodels
    - mpmath
    - matplotlib-base

test:
  imports:
    - blitzgsea
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/maayanlab/blitzgsea
  summary: Package for fast and accurate calculation of Gene Set Enrichment Analysis (GSEA) similar to prerank using gamma distribution approximation.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wxicu
